version: '3.5'

services:
  postgres:
    container_name: moments_postgres
    image: postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '${PG_PORT}:5432'
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge
volumes:
  postgres:
